const config = {
  plugins: {
    // Parse modern OKLab/OKLCH color functions generated by Tailwind
    "@csstools/postcss-oklab-function": {},
    "@tailwindcss/postcss": {},
  },
};

export default config;    